# Generated by Django 4.2 on 2023-04-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='baby',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Boy'), (2, 'Girl')]),
        ),
    ]
