# Generated by Django 4.2 on 2023-04-09 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0002_alter_baby_age_alter_baby_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaper',
            name='date',
        ),
        migrations.RemoveField(
            model_name='diaper',
            name='dirty',
        ),
        migrations.RemoveField(
            model_name='diaper',
            name='wet',
        ),
    ]
