# Generated by Django 4.2 on 2023-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0003_remove_diaper_date_remove_diaper_dirty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaper',
            name='diaper',
            field=models.IntegerField(choices=[(1, 'Wet 💦'), (2, 'Dirty 💩')], default=1),
        ),
    ]
