# Generated by Django 4.2 on 2023-04-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0004_diaper_diaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaper',
            old_name='time',
            new_name='log',
        ),
    ]
