# Generated by Django 4.2 on 2023-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0005_rename_time_diaper_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='age',
        ),
        migrations.AddField(
            model_name='baby',
            name='dob',
            field=models.DateField(default='2019-01-01'),
        ),
    ]
