# Generated by Django 4.2 on 2023-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0006_remove_baby_age_baby_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='dob',
            field=models.DateField(default='timezone.now'),
        ),
    ]
