# Generated by Django 4.2 on 2023-04-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0008_alter_baby_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affirmation',
            name='date',
        ),
    ]
