# Generated by Django 4.2 on 2023-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0009_remove_affirmation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaper',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
