# Generated by Django 4.2 on 2023-04-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0010_alter_diaper_notes_alter_feeding_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='time',
            new_name='log',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='date',
        ),
    ]
