# Generated by Django 4.2 on 2023-04-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0011_rename_time_feeding_log_remove_feeding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='duration',
        ),
    ]
