# Generated by Django 4.2 on 2023-04-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babybliss', '0013_alter_feeding_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaper',
            name='baby',
        ),
    ]
